working on rest api

diff --git a/runMavenProfile b/runMavenProfile
--- a/runMavenProfile
+++ b/runMavenProfile
@@ -6,13 +6,18 @@ usage() {
 
 sdk() {
     set -u
-    cd sdk/src/main/java/org/zstack/sdk/
-    find . -type f  | grep -E -v "(ZSClient|ZSConfig|ApiException|AsyncRestState|Completion|Constants|ErrorCode|ErrorCodeList|InternalCompletion|ApiResult|Param|RestInfo|AbstractAction|QueryAction).java" | xargs rm -f
-    cd -
     rm -rf ~/zstack-sdk/java
     cd test
     mvn test -Dtest=TestGenerateSDK
+    if [ $? -ne 0 ]; then
+	echo "if you see a compile error, you may try to compile and install the sdk module first"
+	exit 1
+    fi
     cd - > /dev/null
+
+    cd sdk/src/main/java/org/zstack/sdk/
+    find . -type f  | grep -E -v "(ZSClient|ZSConfig|ApiException|AsyncRestState|Completion|Constants|ErrorCode|ErrorCodeList|InternalCompletion|ApiResult|Param|RestInfo|AbstractAction|QueryAction).java" | xargs rm -f
+    cd -
     yes | cp ~/zstack-sdk/java/* sdk/src/main/java/org/zstack/sdk/
     set +u
 }
